#generator = Program ('m68kmake.c')
#gencode = Command ('m68kops.h', 'm68k_in.c', ['./m68kmake'])
#Depends (gencode, generator)
env = Environment()
env.Append(CCFLAGS = '-Wall -g')
env.Program ('vade', ['vade.c'] + Glob ('Musashi/*.c'))
