env = Environment()
env.Replace(CC = 'clang', CXX = 'clang++')
env.Append(CCFLAGS = '-m32 -Wall -g')
env.Append(CXXFLAGS = '-std=c++11 -m32 -Wall -g -I/opt/local/include -I/usr/local/include -I/opt/m68k-amigaos/os-include')
env.Append(LINKFLAGS = '-arch i386')
env.Program('vadm', Glob('*.cxx') + Glob ('Musashi/*.c'), LIBS = ['log4cxx', 'PocoFoundation'], LIBPATH = ['/opt/local/lib', '/usr/local/lib'])
