import sys
import os

env = Environment(CC        = '/opt/m68k-amigaos/bin/m68k-amigaos-gcc', 
                  CFLAGS    = os.getenv('CFLAGS', ''),
                  LINKFLAGS = '-s -nostdlib',
                  ENV       = {'PATH': ['/opt/local/bin', '/usr/local/bin', '/bin', '/usr/bin']})
if sys.platform.startswith('linux'):
    env.Append(CFLAGS = ' -Wall -I/usr/include -I/usr/include/i386-linux-gnu -D__KLIBC__')
else:
    env.Append(CFLAGS = ' -Wall -IExamples/linux-usr-include -IExamples/linux-usr-include/i386-linux-gnu -D__KLIBC__')
Export('env')

SConscript(['klibc/SConscript', 'libgcc/SConscript'])

env.Program('strtoupper', ['strtoupper.c'])
env.Program('amihello', ['cwcrt0.c', 'amihello.c'])
env.Program('amifind', ['cwcrt0.c', 'amifind.c'] + Glob('klibc/*.o') + Glob('libgcc/*.o'))
env.Program('memtest', ['cwcrt0.c', 'memtest.c'])
