import os

sources = Split('__divsi3.c __modsi3.c __udivdi3.c __udivmoddi4.c __udivmodsi4.c __umoddi3.c')

Import('env')
for fname in sources:
    if os.path.exists(fname + '.patch'):
        env.Command(fname, fname + '.patch', 
            'wget -q -PExamples/libgcc https://raw.githubusercontent.com/brainflux/klibc/master/usr/klibc/libgcc/' + fname + 
            ' && patch $TARGET $SOURCE')
    else:
        env.Command(fname, [],
            'wget -q -PExamples/libgcc https://raw.githubusercontent.com/brainflux/klibc/master/usr/klibc/libgcc/' + fname)
    env.Object(fname)

