import os

sources = Split('memset.c snprintf.c strchr.c strcmp.c strlen.c strncat.c strncpy.c vsnprintf.c')

Import('env')
for fname in sources:
    if os.path.exists(fname + '.patch'):
        env.Command(fname, fname + '.patch', 
            'wget -q -PExamples/klibc https://raw.githubusercontent.com/brainflux/klibc/master/usr/klibc/' + fname + 
            ' && patch $TARGET $SOURCE')
    else:
        env.Command(fname, [],
            'wget -q -PExamples/klibc https://raw.githubusercontent.com/brainflux/klibc/master/usr/klibc/' + fname)
    env.Object(fname)

